name: HSSkills
version: '${project.version}'
main: net.highskiesmc.hsskills.HSSkills
api-version: 1.13
authors: [ Daniel Ohrin ]
description: Player (Rank) Skills for High Skies
depend: [ SuperiorSkyblock2, RoseStacker, HSNodes, HSProgression, HSMisc, HSAdventure ]
commands:
  skills:
    description: "Opens the menu for player skills"
  hsskills:
    description: "Admin commands for HSSkills"