name: HSSkills
version: '${project.version}'
main: net.highskiesmc.hsskills.HSSkills
api-version: 1.13
authors: [ Daniel Ohrin ]
description: Player (Rank) Skills for High Skies
commands:
  skills:
    description: "Opens the menu for player skills"
  getskilltoken: